### ISSUE TITLE
Incorrect visualization of the solution

### ISSUE THREAD

**Issue by lxily** [CG-SHOP/pyutils24#2]
Hi~, the plot_solution() function in visualization\plot.py does not work properly. It appears that each polygon requires the addition of the first point to create closure for correct visualization, as follows:

```
def plot_solution(ax: plt.Axes, instance, solution):
    ....
    fpoly = instance["items"][idx]
    fpoly["x"].append(fpoly["x"][0])
    fpoly["y"].append(fpoly["y"][0])
    ....
```

**Comment by d-krupke** [comment]
Hey,
Thanks for reporting the error! We will take care of it with the next update.
Best,
Dominik

**Comment by d-krupke** [comment]
Should be fixed with the latest release. Let me know if you notice any further errors. Thanks again!

**Comment by lxily** [comment]
It works well now, thank you for your very helpful tools!
