### ISSUE TITLE
Python.h: No such file or directory

### ISSUE THREAD

**Issue by gfonsecabr** [CG-SHOP/pyutils24#3]
The installation instructions could say that you need to have python3-devel installed. Otherwise, #include <Python.h> gives an error. For installation instructions on several distributions check:

https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by d-krupke** [comment]
Interesting. Haven't seen that before. Would have expected this to be installed by default with every Python environment. Will extend the instructions, thanks for the link!

**Comment by d-krupke** [comment]
I added a corresponding comment and extended the trouble-shooting section of skbuild-conan accordingly.

Thanks for the suggestion!
